// Mock data for Purchase Orders
const mockPOs = [
    {
        poNumber: "PO-2023-001",
        supplier: "Acme Inc.",
        supplierCode: "S011395",
        description: "Office Supplies - Paper, Pens, and Staplers",
        poDate: "4/1/2023",
        dueDate: "5/15/2023",
        createdDate: "4/1/2023",
        orderedQuantity: 100,
        shippedQuantity: 0,
        receivedQuantity: 0,
        pendingQuantity: 100,
        unit: "boxes",
        unitPrice: 25.5,
        currency: "USD",
        location: "New York",
        leadTime: 30,
        shipmentAdvice: null,
        grnNumber: null,
        status: "immediate-action",
        statusText: "Delayed",
        remarks: "Supplier has not confirmed order",
        piNo: "PI-2023-001",
        compCode: "793LLC",
        poTxn: "IPOCT",
        saTxn: "0",
        deliveryTerm: "FOB-FREE ON BOARD",
        items: 1
    },
    {
        poNumber: "PO-2023-002",
        supplier: "Local Vendors",
        supplierCode: "S007547",
        description: "Office Furniture - Desks and Chairs",
        poDate: "4/2/2023",
        dueDate: "5/10/2023",
        createdDate: "4/2/2023",
        orderedQuantity: 25,
        shippedQuantity: 25,
        receivedQuantity: 25,
        pendingQuantity: 0,
        unit: "sets",
        unitPrice: 750.0,
        currency: "USD",
        location: "Dallas",
        leadTime: 30,
        shipmentAdvice: "SA-2023-002",
        grnNumber: "GRN-2023-002",
        status: "grn",
        statusText: "Received",
        remarks: "All items received in good condition",
        piNo: "PI-2023-002",
        compCode: "793LLC",
        poTxn: "IPOCT",
        saTxn: "ISA",
        deliveryTerm: "FOB-FREE ON BOARD",
        items: 1
    },
    {
        poNumber: "PO-2023-003",
        supplier: "Prime Suppliers",
        supplierCode: "S011014",
        description: "Electronics - Laptops and Monitors",
        poDate: "4/3/2023",
        dueDate: "5/12/2023",
        createdDate: "4/3/2023",
        orderedQuantity: 50,
        shippedQuantity: 50,
        receivedQuantity: 50,
        pendingQuantity: 0,
        unit: "units",
        unitPrice: 1200.0,
        currency: "USD",
        location: "Miami",
        leadTime: 35,
        shipmentAdvice: "SA-2023-003",
        grnNumber: "GRN-2023-003",
        status: "grn",
        statusText: "Received",
        remarks: "All items received and tested",
        piNo: "PI-2023-003",
        compCode: "793LLC",
        poTxn: "IPOCT",
        saTxn: "ISA",
        deliveryTerm: "FOB-FREE ON BOARD",
        items: 1
    },
    {
        poNumber: "PO-2023-005",
        supplier: "Global Supplies",
        supplierCode: "S013468",
        description: "Cleaning Supplies - Industrial Grade",
        poDate: "4/5/2023",
        dueDate: "5/18/2023",
        createdDate: "4/5/2023",
        orderedQuantity: 200,
        shippedQuantity: 0,
        receivedQuantity: 0,
        pendingQuantity: 200,
        unit: "boxes",
        unitPrice: 45.75,
        currency: "USD",
        location: "London",
        leadTime: 40,
        shipmentAdvice: null,
        grnNumber: null,
        status: "immediate-action",
        statusText: "Missing Data",
        remarks: "Supplier information incomplete",
        piNo: "PI-2023-005",
        compCode: "826LLC",
        poTxn: "IPOCT",
        saTxn: "0",
        deliveryTerm: "FOB-FREE ON BOARD",
        items: 1
    },
    {
        poNumber: "PO-2023-008",
        supplier: "Overseas Exports",
        supplierCode: "S003735",
        description: "Raw Materials - Steel Sheets",
        poDate: "4/10/2023",
        dueDate: "5/25/2023",
        createdDate: "4/10/2023",
        orderedQuantity: 150,
        shippedQuantity: 150,
        receivedQuantity: 0,
        pendingQuantity: 0,
        unit: "tons",
        unitPrice: 1800.0,
        currency: "USD",
        location: "Shanghai",
        leadTime: 45,
        shipmentAdvice: "SA-2023-008",
        grnNumber: null,
        status: "transit",
        statusText: "In Transit",
        remarks: "Shipment en route, expected arrival on schedule",
        piNo: "PI-2023-008",
        compCode: "826LLC",
        poTxn: "IPOCT",
        saTxn: "ISA",
        deliveryTerm: "FOB-FREE ON BOARD",
        items: 1
    },
    {
        poNumber: "PO-2023-010",
        supplier: "Fast Shipping",
        supplierCode: "S011739",
        description: "Packaging Materials - Boxes and Tape",
        poDate: "4/12/2023",
        dueDate: "5/28/2023",
        createdDate: "4/12/2023",
        orderedQuantity: 500,
        shippedQuantity: 500,
        receivedQuantity: 0,
        pendingQuantity: 0,
        unit: "sets",
        unitPrice: 12.25,
        currency: "USD",
        location: "Singapore",
        leadTime: 30,
        shipmentAdvice: "SA-2023-010",
        grnNumber: null,
        status: "transit",
        statusText: "In Transit",
        remarks: "Shipment delayed by 2 days due to weather",
        piNo: "PI-2023-010",
        compCode: "733LLC",
        poTxn: "IPOCT",
        saTxn: "ISA",
        deliveryTerm: "FOB-FREE ON BOARD",
        items: 1
    },
    {
        poNumber: "PO-2023-012",
        supplier: "Tech Components",
        supplierCode: "S013465",
        description: "Electronic Components - Circuit Boards",
        poDate: "4/15/2023",
        dueDate: "6/10/2023",
        createdDate: "4/15/2023",
        orderedQuantity: 1000,
        shippedQuantity: 0,
        receivedQuantity: 0,
        pendingQuantity: 1000,
        unit: "pieces",
        unitPrice: 8.50,
        currency: "USD",
        location: "San Francisco",
        leadTime: 50,
        shipmentAdvice: null,
        grnNumber: null,
        status: "production",
        statusText: "In Production",
        remarks: "Production started, on schedule",
        piNo: "PI-2023-012",
        compCode: "793LLC",
        poTxn: "IPOCT",
        saTxn: "0",
        deliveryTerm: "FOB-FREE ON BOARD",
        items: 2
    },
    {
        poNumber: "PO-2023-015",
        supplier: "Quality Parts",
        supplierCode: "S011395",
        description: "Machine Parts - Gears and Bearings",
        poDate: "4/20/2023",
        dueDate: "6/15/2023",
        createdDate: "4/20/2023",
        orderedQuantity: 300,
        shippedQuantity: 0,
        receivedQuantity: 0,
        pendingQuantity: 300,
        unit: "sets",
        unitPrice: 65.30,
        currency: "USD",
        location: "Chicago",
        leadTime: 45,
        shipmentAdvice: null,
        grnNumber: null,
        status: "production",
        statusText: "In Production",
        remarks: "Production in progress, 30% complete",
        piNo: "PI-2023-015",
        compCode: "793LLC",
        poTxn: "IPOCT",
        saTxn: "0",
        deliveryTerm: "FOB-FREE ON BOARD",
        items: 1
    }
];

// Function to get POs by status
function getPOsByStatus(status) {
    if (status === 'all') {
        return mockPOs;
    }
    return mockPOs.filter(po => po.status === status);
}

// Function to get PO by number
function getPOByNumber(poNumber) {
    return mockPOs.find(po => po.poNumber === poNumber);
}

// Function to search POs
function searchPOs(query) {
    query = query.toLowerCase();
    return mockPOs.filter(po => 
        po.poNumber.toLowerCase().includes(query) ||
        po.supplier.toLowerCase().includes(query) ||
        po.description.toLowerCase().includes(query) ||
        po.location.toLowerCase().includes(query)
    );
}